name: All Tests

on:
  schedule:
    # Run full test suite daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yaml

  integration-tests:
    uses: ./.github/workflows/integration-test.yaml
    secrets: inherit

  test-summary:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: always()

    steps:
      - name: Test Summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Unit Tests: ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Integration Tests: ${{ needs.integration-tests.result }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.unit-tests.result }}" == "success" && "${{ needs.integration-tests.result }}" == "success" ]]; then
            echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some tests failed!" >> $GITHUB_STEP_SUMMARY
            exit 1
